### ISSUE TITLE
Hi, is that possible relay an onnx model more than 7.6GB?

### ISSUE THREAD

**Issue by lucasjinreal** [AndrewZhaoLuo/TVM-Sandbox#1]
As you know, this model is GPT2-large. just wonder does it possible to quantize such a giant model through tvm?

**Comment by AndrewZhaoLuo** [comment]
You can't quantize in TVM right now I believe (or it isn't very complete).

But if you have a model already quantized you can use TVM. I've done GPT2 before (though not the large variant).

**Comment by lucasjinreal** [comment]
@AndrewZhaoLuo are u using hugging face quantized the model? do u have a simple tutorial on how does it quantized?

**Comment by AndrewZhaoLuo** [comment]
Hmm, I don't know, it was a model that a few friends had lying around. Not sure to be honest.
